### ISSUE TITLE
Suggestion: Option to enable Full Tilt! gameplay rules instead of 3D Pinball's

### ISSUE THREAD

**Issue by win98se** [k4zmu2a/SpaceCadetPinball#57]
> There are only a few minor differences between the gameplay of the two versions. The completion of a mission in the Maxis version results in a replay—actually a ball save, rather than a special—being awarded. In addition, hitting a wormhole that has the same color light locks the ball, which if done repeatedly activates the multi-ball round. This is not the case in 3D Pinball: Completing a mission merely awards bonus points and hitting a wormhole in the above circumstances awards a replay. Also, the three yellow lights above the bumpers (both in the launch ramp and in the upper table zone) act differently: In 3D Pinball these are turned off if the ball passes on them while they are on. This is not the case in the original game, where they just remain activated.

Source: https://en.wikipedia.org/wiki/Full_Tilt!_Pinball#3D_Pinball_for_Windows_%E2%80%93_Space_Cadet

I prefer the Full Tilt! gameplay rules, feeling that it's more fun using them instead of 3D Pinball's.

**Comment by k4zmu2a** [comment]
That is a planned feature.
Maybe not as an option, rather based on game data.

I will have to further decompile FT for this, ouch.

**Comment by dobragab** [comment]
I played a bit with the 16 bit Fill Tilt version, and I noticed the following differences:

- wormhole relaunches the ball
- redeploy autolaunches the ball
- mission selector sound is sound52 only if maxed out, not at every hit
- mission selected gains 100k
- text is centered
- sometimes score value is printed within the text
- bumpers move slower
- mission finished gains jackpot 500k+
- mission finished grants replay, like wormhole should (are they stackable?)
- second hyperspce hit grants "jackpot DOUBLED"
- ~jackpot activated and bonus activated are swapped~ wrong by manual
- field multiplier applies to all scores?
- score values might be entirely different, need to double check from manual
- upgrader lights are never turned off by the ball, only on

I hope these are clear, I didn't make these documentation-ready explanations.

**Comment by k4zmu2a** [comment]
This list helps, thank you.
I am adding the differences based on FT decompilation rather than observed behavior.
But it still helps to know what to look for.

Some things I might skip if they are too complex, like flipper physics differences.

**Comment by k4zmu2a** [comment]
I have implemented a lot of FT behaviors in V2.1.0.
Let me know if I missed something.

**Comment by limelier** [comment]
This feature is very nice, though I'd still personally like an option if such a thing is possible. I prefer the 3D Pinball: Space Cadet gameplay (out of nostalgia and muscle memory), but it'd be very cool to be able to play on the higher quality Full Tilt graphics instead.

**Comment by Randomno** [comment]
> I have implemented a lot of FT behaviors in V2.1.0. Let me know if I missed something.

I haven't checked all of @dobragab's list, but I noticed while playing that the automatic re-deploy is not implemented.

**Comment by Oatmeal386** [comment]
@k4zmu2a Completed missions still don't award replays, and as for them stacking, you can only have one at a time.

**Comment by matteoadamo23-art** [comment]
Hi @k4zmu2a. I playing 3D Pinball Space Cadet for Android port (Working in progress). I trying to replace the PINBALL.DAT file to CADET.DAT included CADET.BMP, but the resolution and the sprite only changed... I trying the put and modify the C++ files in the assets folder but not changed nothing, multiball, auto re-deploy nothing. Maybe using Android Studio with the PC and C++ to modify the files example: pb.cpp, TPinballTable.cpp exetera and recompiling the game.

**Comment by matteoadamo23-art** [comment]
@k4zmu2a I tried the PC port and I am funny, writing "Hidden Test" the Cheat code for 3D Pinball version, pressing B, you have got the another ball at left exit of the fucsia ship.

**Comment by markrlucas** [comment]
Why??
